# Generated by Django 4.2.3 on 2023-08-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevesParClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Élèves par Classe',
                'verbose_name_plural': 'Élèves par Classe',
                'db_table': 'elevesparclasse',
                'managed': False,
            },
        ),
    ]
