# Generated by Django 4.2.3 on 2023-08-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_elevesparclasse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AjoutNotes',
        ),
        migrations.DeleteModel(
            name='ElevesParClasse',
        ),
    ]
