# Generated by Django 4.2.4 on 2023-08-10 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_delete_ajoutnotes_delete_elevesparclasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjouterNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=10)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.matiere')),
            ],
            options={
                'db_table': 'ajouter_notes',
                'managed': True,
            },
        ),
    ]
