# Generated by Django 4.2.4 on 2023-08-10 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_ajouternotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteClasse6eme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.matiere')),
            ],
            options={
                'db_table': 'note_classe',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NoteClasse5eme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.matiere')),
            ],
            options={
                'db_table': 'note_classe_',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NoteClasse4eme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.matiere')),
            ],
            options={
                'db_table': 'note_classe_4eme',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NoteClasse3eme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.matiere')),
            ],
            options={
                'db_table': 'note_classe_3eme',
                'managed': True,
            },
        ),
    ]
