# Generated by Django 4.2.3 on 2023-08-10 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0005_noteclasse6eme_noteclasse5eme_noteclasse4eme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.matiere')),
            ],
            options={
                'db_table': 'notes_eleve',
                'managed': True,
            },
        ),
    ]
